title: "HKU Systems Group Events"
description: "Collection of events and seminars hosted by HKU Systems Group"
baseurl: ""
url: "https://hku-systems.github.io/events"

markdown: kramdown
theme: jekyll-theme-cayman

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

include:
  - seminars