layout: page
title: "HKU ISCAS 2021 
Launching Seminar and Workshop Schedule 
(9.28 Tuesday)"
permalink: /events/hku-iscas-2021

lsi: false
safe: true
incremental: false
highlighter: rouge
markdown: kramdown
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-cayman

github:
  is_project_page: false
